from: mac

scm:
  increment: true
  checkout: true

envs:
  version: 3.0.1

stages:
  build:
    - pwd
    - ls
    - rm -rf ./bin/
    - plugin_unity3d_install -v 5.6.1f1 --username "#{unity.username}" --password "#{unity.password}"
    
    # Unity3D引擎游戏客户端工程构建 
    
    # Usage: <main class> [options]
    #   Options:
    #     --apkName
    #        指定安卓APK包的输出名称
    #        Default: output.apk
    #     --apkPath
    #        指定安卓APK包的输出路径，相对于源码仓库根目录的路径
    #        Default: bin/android/
    #     -d, --debug
    #        指定是否采用Debug模式编译
    #        Default: false
    #     --enableBitCode
    #        启用或禁用bitCode模式, 未设置则保持Unity3D生成的xcodeproj工程文件格式
    #     -e, --executeMethod
    #        指定构建脚本的静态入口函数，本插件无需编写C#构建脚本，不指定该参数将自动导入/Assets/Editor/SODABuild.cs脚本，否则使用工程代码中的静态入口函数方法
    #     --keyAliasName
    #        指定安卓平台下的Key别名名称
    #     --keyAliasPass
    #        指定安卓平台下的Key别名密码
    #     --keyStoreName
    #        指定安卓平台下的KeyStore文件，相对与源码仓库根目录的相对路径和文件名
    #     --keyStorePass
    #        指定安卓平台下KeyStore文件的密码
    #     -p, --platforms
    #        指定一个或多个构建包目标平台，多个参数使用","号分割
    #        Default: [android, iphone]
    #     -r, --rootDir
    #        指定工程相对于源码仓库的相对路径
    #     --xcodeProjectName
    #        指定输出的XCode工程名称
    #        Default: XCodeProject
    
    - plugin_unity3d -p iphone
    
    # 调用XCode执行IOS工程构建 
    
    # Usage: <main class> [options]
    #   Options:
    #     --codeSignIdentity
    #        XCode 签名标识
    #        Default: <empty string>
    #     --codeSigningRequired
    #        是否需要签名
    #     -c, --configuration
    #        XCode 工程配置信息
    #     --iosName
    #        IOS IPA名, 默认是output.ipa
    #        Default: output.ipa
    #     --iosPath
    #        IOS IPA所在的目录， 默认是bin/ios
    #        Default: bin/ios
    #     -p, --project
    #        XCode 工程名称
    #     --provisionMethod
    #        XCode 签名证书类型，默认是development
    #        Default: development
    #     --provisioningProfile
    #        XCode 签名profile
    #        Default: <empty string>
    #     -r, --rootDir
    #        XCode 工程的根目录
    #        Default: .
    #     -s, --scheme
    #        XCode 工程scheme
    #     --xCodePath
    #        XCode安装目录，默认是/Applications/Xcode.app/
    #     -x, --xCodeVersion
    #        XCode 版本，如果不指定就用最新的
    
    - plugin_xcode
        
      
    - plugin_fir --build "#{version}" --bundleId com.slicol.snake --file bin/ios/output.ipa  --name Snake --token "#{fir.token}" --type iphone --version "#{version}"
